# This workflow will install Python dependencies, run tests and lint with a single version of Python.
# If tests are not failed, docker image will be created and published in Docker Hub repository.

name: Python application

on:
  push:
    branches:
      - main
  schedule:
    - cron: '35 11 * * *'

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install software
      run: sudo apt-get install -y chromium-browser
    - name: Install the necessary packages
      run: |
        python -m pip install --upgrade pip
        pip install webdriver-manager selenium pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest
  
  publish:

    runs-on: ubuntu-latest
    
    needs: test

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push register app
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/test:latest
  
